### ISSUE TITLE
Additional builder operations

### ISSUE THREAD

**Issue by burtlo** [rayh/xcoder#18]
I have some code that I personally have [monkeypatched](https://github.com/burtlo/xcoder-cedar/blob/master/lib/xcode/builder_cedar.rb) onto Xcoder to provide support for running [Cedar](https://github.com/pivotal/cedar) from a `Builder` object. I thought maybe Xcoder could implement some [plugin system](https://github.com/burtlo/xcoder/commit/f548654c4d3bb40f56ae9c0ae4b56e61f0fc768c) that could auto require gems with a prefixed name **xcoder-**.

I linked a branch I created awhile back that implements a rudimentary solution to this problem. I was wondering if you had any thoughts about allowing a more formal way to allow for additional tools. Whether we should just include them in the gem or talk about some plugin system.

If we did choose a plugin system I think that it would likely be a good idea to not have the plugins just monkey-patch like I have done and instead do something like a DSL that add's available tasks to the Builder's that are created.

``` ruby

Xcode::Builder.add_task :cedar do

      require 'tmpdir'

      cmd = BuildCommand.new

      # Similar to the xcoder gem these platform values and paths are hard-coded.
      # This is likely a poor choice and one that will get this little plugin
      # into some trouble when the iOS library upgrades.

      cmd << "DYLD_ROOT_PATH=\"/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.0.sdk\""
      cmd << "IPHONE_SIMULATOR_ROOT=\"/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.0.sdk\""

      tempHome = Dir.mktmpdir("Cedar")
      Dir.mkdir File.join(tempHome, "Documents")
      Dir.mkdir File.join(tempHome, "Library")
      Dir.mkdir File.join(tempHome, "Library/Preferences")
      Dir.mkdir File.join(tempHome, "Library/Caches")
      Dir.mkdir File.join(tempHome, "tmp")

      cmd << "CFFIXED_USER_HOME=#{tempHome}"
      cmd << "CEDAR_HEADLESS_SPECS=1"
      cmd << "CEDAR_REPORTER_CLASS=CDRColorizedReporter"
      cmd << "CEDAR_REPORTER_OPTS=nested"

      cmd << "\"#{@build_path}#{@config.name}-iphonesimulator/#{@target.name}.app/#{@target.name}\""
      cmd << "-RegisterForSystemEvents"

      yield cmd if block_given?

      Xcode::Shell.execute(cmd.to_a)

end

```

**Comment by rayh** [comment]
I never really intended for xcoder to be a rake-style build/task
management thing, rather a toolset that something like rake could use.
 Although builder does some basic lifecycle things, I'm not sure if it
needs to have additional steps defined on it in this way.

Perhaps we need a model for building Xcode commands, like we spoke of
before, and that can be used by third-parties to easily build and
invoke commands within the context of a builder (probably a bad name
for it, perhaps build_context would be better?).  Perhaps something
like:

builder.call :xcodebuild do |context, command|
  command.add_build_param "DYLD_ROOT_PATH",
"/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.0.sdk"
  command.add_path_arg
"#{context.build_path}#{context.config.name}-iphonesimulator/#{context.target.name}.app/#{context.target.name}"
  command.add_arg              "-RegisterForSystemEvents"
end

The idea being that remove the need for the caller to have to worry
about escaping of paths, assembling KEY=value pairs, etc, and it gives
us some context around the values being supplied. The block also gets
passed the build_context (currently the builder) so that you can
access config, target, etc

Thoughts?

On 5 March 2012 11:16, Franklin Webber
reply@reply.github.com
wrote:

> I have some code that I personally have [monkeypatched](https://github.com/burtlo/xcoder-cedar/blob/master/lib/xcode/builder_cedar.rb) onto Xcoder to provide support for running [Cedar](https://github.com/pivotal/cedar) from a `Builder` object. I thought maybe Xcoder could implement some [plugin system](https://github.com/burtlo/xcoder/commit/f548654c4d3bb40f56ae9c0ae4b56e61f0fc768c) that could auto require gems with a prefixed name **xcoder-**.
> 
> I linked a branch I created awhile back that implements a rudimentary solution to this problem. I was wondering if you had any thoughts about allowing a more formal way to allow for additional tools. Whether we should just include them in the gem or talk about some plugin system.
> 
> If we did choose a plugin system I think that it would likely be a good idea to not have the plugins just monkey-patch like I have done and instead do something like a DSL that add's available tasks to the Builder's that are created.
> 
> ``` ruby
> 
> Xcode::Builder.add_task :cedar do
> 
>      require 'tmpdir'
> 
>      cmd = BuildCommand.new
> 
>      # Similar to the xcoder gem these platform values and paths are hard-coded.
>      # This is likely a poor choice and one that will get this little plugin
>      # into some trouble when the iOS library upgrades.
> 
>      cmd << "DYLD_ROOT_PATH=\"/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.0.sdk\""
>      cmd << "IPHONE_SIMULATOR_ROOT=\"/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.0.sdk\""
> 
>      tempHome = Dir.mktmpdir("Cedar")
>      Dir.mkdir File.join(tempHome, "Documents")
>      Dir.mkdir File.join(tempHome, "Library")
>      Dir.mkdir File.join(tempHome, "Library/Preferences")
>      Dir.mkdir File.join(tempHome, "Library/Caches")
>      Dir.mkdir File.join(tempHome, "tmp")
> 
>      cmd << "CFFIXED_USER_HOME=#{tempHome}"
>      cmd << "CEDAR_HEADLESS_SPECS=1"
>      cmd << "CEDAR_REPORTER_CLASS=CDRColorizedReporter"
>      cmd << "CEDAR_REPORTER_OPTS=nested"
> 
>      cmd << "\"#{@build_path}#{@config.name}-iphonesimulator/#{@target.name}.app/#{@target.name}\""
>      cmd << "-RegisterForSystemEvents"
> 
>      yield cmd if block_given?
> 
>      Xcode::Shell.execute(cmd.to_a)
> 
> end
> 
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rayh/xcoder/issues/18

## 

## Ray Hilton

a: 13/243 Collins Street, Melbourne VIC 3000
m: 0430 484 708
w: http://rayh.com.au

**Comment by burtlo** [comment]
I like what you are proposing as a way to add build parameters, arguments, and environment variables. I think that this could provide an easy way for **Cedar** and similar libraries, the ability to provide a simple way to integrate with **Xcoder**.

I'll take some time to work on this to support some articles that I am writing.

**Comment by rayh** [comment]
I'm going to close this as the nature of builder and the way commands get executed has changed slightly.
