### ISSUE TITLE
KIF Output Parser

### ISSUE THREAD

**Issue by blakewatters** [rayh/xcoder#31]
Wanted to gauge interest in merging support for a KIF output formatter. We have a suite of KIF (http://github.com/square/KIF) scenarios for functionally testing out application and I have just configured xcoder to build it. Am working on installing into Jenkins for CI now. If I knocked out a parser for presenting KIF output in a format similar to the SenTest output, would there be interest in merging it?

**Comment by rayh** [comment]
That sounds like a good idea.  The builder currently uses the OCUnit parser directly, but I guess we could have an optional argument to the test method that tells it what parser to use, defaulting to OCUnit.  I might do some prelim work to allow the easy addition of additional parsers

**Comment by burtlo** [comment]
I +1 all modularity!

**Comment by rayh** [comment]
I've done some work so that the abstract representation of test reports from the parsing.  Please take a look and see if you can add a new parser that can manipulate the same common report model (take a look at the OCUnitParser).  It's by no means a complete separation of concerns, but hopefully it helps.
