### ISSUE TITLE
Incorrect project path used when building Rakefile with 'xcoder/rake_task'

### ISSUE THREAD

**Issue by joshhepworth** [rayh/xcoder#45]
When requiring `xcoder/rake_task` and using `Xcode::Raketask.new` from within the project's root, the Rake task tries to load the project file from the wrong location.

```
Project git:develop ❯ rake -T                                                    ✭
rake aborted!
Failed to correctly parse the project file /Users/Josh/Dropbox/Development/Repos/Project/Project.xcodeproj/Project.xcodeproj/project.pbxproj

(See full trace by running task with --trace)
```

It seems to include the `.xcodeproj` file twice in the path it builds.

**Comment by burtlo** [comment]
I will take a look.

**Comment by burtlo** [comment]
@joshhepworth from the example above, what is your current directory?

I have a Test project located in the folder `test`. I tried executing `rake -T` from within `test` and `test/Test.xcodeproj` and I don't see the same error.

I do believe another error can occur when there are some errors when the `parse_schemes` starts running and there are some old schemes that do not match up in some way.

If you could, try and run the command again, this time with `rake -T --trace` and post the full stack trace.

If the issue is related to `parse_schemes`, you likely can address it by removing the offending scheme from `Project/Project.xcodeproj/xcuserdata/USERNAME.xcuserdatad/xcschemes/`

**Comment by joshhepworth** [comment]
If I created a completely new project with Xcode and used the rake tasks, there was no error so I tried playing around with the xcscheme file which got it working. Thanks.

**Comment by burtlo** [comment]
There is still a good issue that you found, that we should address with schemes. I have run into this problem before and it is annoying to try and troubleshoot.
