### ISSUE TITLE
TestFlight Broken in 0.1.14

### ISSUE THREAD

**Issue by mhupman** [rayh/xcoder#50]
It seems like the changes to Shell.rb and the introduction of Command.rb broke the TestFlight integration class.  The error seems to be that TestFlight.rb is still using the old Array method of constructing shell commands.

**Comment by rayh** [comment]
Whoops, I'll get straight on it

On 06/12/2012, at 3:36, mhupman notifications@github.com wrote:

It seems like the changes to Shell.rb and the introduction of Command.rb
broke the TestFlight integration class. The error seems to be that
TestFlight.rb is still using the old Array method of constructing shell
commands.

—
Reply to this email directly or view it on
GitHubhttps://github.com/rayh/xcoder/issues/50.

**Comment by rayh** [comment]
I have also been meaning to move the code to be pure ruby, rather than
relying on curl, and maybe external using it to allow for other/multiple
distribution services

On 06/12/2012, at 3:36, mhupman notifications@github.com wrote:

It seems like the changes to Shell.rb and the introduction of Command.rb
broke the TestFlight integration class. The error seems to be that
TestFlight.rb is still using the old Array method of constructing shell
commands.

—
Reply to this email directly or view it on
GitHubhttps://github.com/rayh/xcoder/issues/50.

**Comment by rayh** [comment]
Fixed in 0.1.15
